version: "3"
name: projet-esgi-cluster

services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    restart: always
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    environment:
      - "INIT_DAEMON_STEP=setup_spark"
    volumes:
      - ./app:/app

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always
    container_name: spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always
    container_name: spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    restart: always
    container_name: spark-worker-3
    hostname: spark-worker-3
    ports:
      - "8083:8081"
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - ./app:/app

  pyspark-notebook:
      image: jupyter/pyspark-notebook:spark-3.3.0
      restart: always
      container_name: pyspark-notebook
      hostname: pyspark-notebook
      ports:
        - "8888:8888"
      depends_on:
        - spark-master
      environment:
        - "JUPYTER_TOKEN=easy"
      volumes:
        - ./app:/home/jovyan

